package com.vince.vchat12.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.vince.vchat12.data.Group;
import com.vince.vchat12.data.Friends;
import com.vince.vchat12.data.LocalMsg;
import com.vince.vchat12.data.Dialogues;

import com.vince.vchat12.data.GroupDao;
import com.vince.vchat12.data.FriendsDao;
import com.vince.vchat12.data.LocalMsgDao;
import com.vince.vchat12.data.DialoguesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupDaoConfig;
    private final DaoConfig friendsDaoConfig;
    private final DaoConfig localMsgDaoConfig;
    private final DaoConfig dialoguesDaoConfig;

    private final GroupDao groupDao;
    private final FriendsDao friendsDao;
    private final LocalMsgDao localMsgDao;
    private final DialoguesDao dialoguesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        friendsDaoConfig = daoConfigMap.get(FriendsDao.class).clone();
        friendsDaoConfig.initIdentityScope(type);

        localMsgDaoConfig = daoConfigMap.get(LocalMsgDao.class).clone();
        localMsgDaoConfig.initIdentityScope(type);

        dialoguesDaoConfig = daoConfigMap.get(DialoguesDao.class).clone();
        dialoguesDaoConfig.initIdentityScope(type);

        groupDao = new GroupDao(groupDaoConfig, this);
        friendsDao = new FriendsDao(friendsDaoConfig, this);
        localMsgDao = new LocalMsgDao(localMsgDaoConfig, this);
        dialoguesDao = new DialoguesDao(dialoguesDaoConfig, this);

        registerDao(Group.class, groupDao);
        registerDao(Friends.class, friendsDao);
        registerDao(LocalMsg.class, localMsgDao);
        registerDao(Dialogues.class, dialoguesDao);
    }
    
    public void clear() {
        groupDaoConfig.getIdentityScope().clear();
        friendsDaoConfig.getIdentityScope().clear();
        localMsgDaoConfig.getIdentityScope().clear();
        dialoguesDaoConfig.getIdentityScope().clear();
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public FriendsDao getFriendsDao() {
        return friendsDao;
    }

    public LocalMsgDao getLocalMsgDao() {
        return localMsgDao;
    }

    public DialoguesDao getDialoguesDao() {
        return dialoguesDao;
    }

}
