package com.vince.vchat12.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUP".
 */
public class Group {

    private Long id;
    private java.util.Date create_time;
    private java.util.Date update_time;
    private String web_id;
    private String group_name;

    public Group() {
    }

    public Group(Long id) {
        this.id = id;
    }

    public Group(Long id, java.util.Date create_time, java.util.Date update_time, String web_id, String group_name) {
        this.id = id;
        this.create_time = create_time;
        this.update_time = update_time;
        this.web_id = web_id;
        this.group_name = group_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getCreate_time() {
        return create_time;
    }

    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

    public java.util.Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(java.util.Date update_time) {
        this.update_time = update_time;
    }

    public String getWeb_id() {
        return web_id;
    }

    public void setWeb_id(String web_id) {
        this.web_id = web_id;
    }

    public String getGroup_name() {
        return group_name;
    }

    public void setGroup_name(String group_name) {
        this.group_name = group_name;
    }

}
